const ctr = [
  { code: 'CO', label: ' (+57) Colombia', phone: '57' },
  {
    code: 'US',
    label: '(+1) United States',
    phone: '1',
    suggested: true,
  },
  { code: 'MX', label: '(+52) Mexico', phone: '52' },

  { code: 'AD', label: '(+376) Andorra', phone: '376' },
  {
    code: 'AE',
    label: '(+971) United Arab Emirates',
    phone: '971',
  },
  { code: 'AF', label: '(+93) Afghanistan', phone: '93' },
  {
    code: 'AG',
    label: 'Antigua and Barbuda',
    phone: '1-268',
  },
  { code: 'AI', label: '(+ 1-264) Anguilla', phone: '1-264' },
  { code: 'AL', label: '(+ 355) Albania', phone: '355' },
  { code: 'AM', label: '(+ 374) Armenia', phone: '374' },
  { code: 'AO', label: '(+ 244) Angola', phone: '244' },
  { code: 'AQ', label: '(+ 672) Antarctica', phone: '672' },
  { code: 'AR', label: '(+ 54) Argentina', phone: '54' },
  { code: 'AS', label: '(+ 1-684) American Samoa', phone: '1-684' },
  { code: 'AT', label: '(+ 43) Austria', phone: '43' },
  {
    code: 'AU',
    label: '(+61) Australia',
    phone: '61',
    suggested: true,
  },
  { code: 'AW', label: '(+297) Aruba', phone: '297' },
  { code: 'AX', label: '(+358) Alland Islands', phone: '358' },
  { code: 'AZ', label: '(+994) Azerbaijan', phone: '994' },
  {
    code: 'BA',
    label: '(+387) Bosnia and Herzegovina',
    phone: '387',
  },
  { code: 'BB', label: '(+1-246) Barbados', phone: '1-246' },
  { code: 'BD', label: '(+880) Bangladesh', phone: '880' },
  { code: 'BE', label: '(+32) Belgium', phone: '32' },
  { code: 'BF', label: '(+226) Burkina Faso', phone: '226' },
  { code: 'BG', label: '(+359) Bulgaria', phone: '359' },
  { code: 'BH', label: '(+973) Bahrain', phone: '973' },
  { code: 'BI', label: '(+257) Burundi', phone: '257' },
  { code: 'BJ', label: '(+229) Benin', phone: '229' },
  { code: 'BL', label: '(+590) Saint Barthelemy', phone: '590' },
  { code: 'BM', label: '(+1-441) Bermuda', phone: '1-441' },
  { code: 'BN', label: '(+673) Brunei Darussalam', phone: '673' },
  { code: 'BO', label: '(+591) Bolivia', phone: '591' },
  { code: 'BR', label: '(+55) Brasil', phone: '55' },
  { code: 'BS', label: '(+1-242) Bahamas', phone: '1-242' },
  { code: 'BT', label: '(+975) Bhutan', phone: '975' },
  { code: 'BV', label: '(+47) Bouvet Island', phone: '47' },
  { code: 'BW', label: '(+267) Botswana', phone: '267' },
  { code: 'BY', label: '(+375) Belarus', phone: '375' },
  { code: 'BZ', label: '(+501) Belize', phone: '501' },
  {
    code: 'CA',
    label: '(+1) Canada',
    phone: '1',
    suggested: true,
  },
  {
    code: 'CC',
    label: '(+61) Cocos (Keeling) Islands',
    phone: '61',
  },
  {
    code: 'CD',
    label: '(+243) Congo, Democratic Republic of the',
    phone: '243',
  },
  {
    code: 'CF',
    label: '(+236) Central African Republic',
    phone: '236',
  },
  {
    code: 'CG',
    label: '(+242) Congo, Republic of the',
    phone: '242',
  },
  { code: 'CH', label: '(+41) Switzerland', phone: '41' },
  { code: 'CI', label: "(+225) Cote d'Ivoire", phone: '225' },
  { code: 'CK', label: '(+682) Cook Islands', phone: '682' },
  { code: 'CL', label: '(+56) Chile', phone: '56' },
  { code: 'CM', label: '(+237) Cameroon', phone: '237' },
  { code: 'CN', label: '(+86) China', phone: '86' },

  { code: 'CR', label: '(+506) Costa Rica', phone: '506' },
  { code: 'CU', label: '(+53) Cuba', phone: '53' },
  { code: 'CV', label: '(+238) Cape Verde', phone: '238' },
  { code: 'CW', label: '(+599) Curacao', phone: '599' },
  { code: 'CX', label: '(+61) Christmas Island', phone: '61' },
  { code: 'CY', label: '(+357) Cyprus', phone: '357' },
  { code: 'CZ', label: '(+420) Czech Republic', phone: '420' },
  {
    code: 'DE',
    label: '(+49) Germany',
    phone: '49',
    suggested: true,
  },
  { code: 'DJ', label: '(+253) Djibouti', phone: '253' },
  { code: 'DK', label: '(+45) Denmark', phone: '45' },
  { code: 'DM', label: '(+1-767) Dominica', phone: '1-767' },
  {
    code: 'DO',
    label: '(+1-809) Dominican Republic',
    phone: '1-809',
  },
  { code: 'DZ', label: '(+213) Algeria', phone: '213' },
  { code: 'EC', label: '(+593) Ecuador', phone: '593' },
  { code: 'EE', label: '(+372) Estonia', phone: '372' },
  { code: 'EG', label: '(+20) Egypt', phone: '20' },
  { code: 'EH', label: '(+212) Western Sahara', phone: '212' },
  { code: 'ER', label: '(+291) Eritrea', phone: '291' },
  { code: 'ES', label: '(+34) España', phone: '34' },
  { code: 'ET', label: '(+251) Ethiopia', phone: '251' },
  { code: 'FI', label: '(+358) Finland', phone: '358' },
  { code: 'FJ', label: '(+679) Fiji', phone: '679' },
  {
    code: 'FK',
    label: '(+500) Falkland Islands (Malvinas)',
    phone: '500',
  },
  {
    code: 'FM',
    label: '(+691) Micronesia, Federated States of',
    phone: '691',
  },
  { code: 'FO', label: '(+298) Faroe Islands', phone: '298' },
  {
    code: 'FR',
    label: '(+33) Francia',
    phone: '33',
    suggested: true,
  },
  { code: 'GA', label: '(+241) Gabon', phone: '241' },
  { code: 'GB', label: '(+44) United Kingdom', phone: '44' },
  { code: 'GD', label: '(+1-473) Grenada', phone: '1-473' },
  { code: 'GE', label: '(+995) Georgia', phone: '995' },
  { code: 'GF', label: '(+594) French Guiana', phone: '594' },
  { code: 'GG', label: '(+44) Guernsey', phone: '44' },
  { code: 'GH', label: '(+233) Ghana', phone: '233' },
  { code: 'GI', label: '(+350) Gibraltar', phone: '350' },
  { code: 'GL', label: '(+299) Greenland', phone: '299' },
  { code: 'GM', label: '(+220) Gambia', phone: '220' },
  { code: 'GN', label: '(+224) Guinea', phone: '224' },
  { code: 'GP', label: '(+590) Guadeloupe', phone: '590' },
  { code: 'GQ', label: '(+240) Equatorial Guinea', phone: '240' },
  { code: 'GR', label: '(+30) Greece', phone: '30' },
  {
    code: 'GS',
    label: '(+500) South Georgia and the South Sandwich Islands',
    phone: '500',
  },
  { code: 'GT', label: '(+502) Guatemala', phone: '502' },
  { code: 'GU', label: '(+1-671) Guam', phone: '1-671' },
  { code: 'GW', label: '(+245) Guinea-Bissau', phone: '245' },
  { code: 'GY', label: '(+592) Guyana', phone: '592' },
  { code: 'HK', label: '(+852) Hong Kong', phone: '852' },
  {
    code: 'HM',
    label: '(+672) Heard Island and McDonald Islands',
    phone: '672',
  },
  { code: 'HN', label: '(+504) Honduras', phone: '504' },
  { code: 'HR', label: '(+385) Croatia', phone: '385' },
  { code: 'HT', label: '(+509) Haiti', phone: '509' },
  { code: 'HU', label: '(+36) Hungary', phone: '36' },
  { code: 'ID', label: '(+62) Indonesia', phone: '62' },
  { code: 'IE', label: '(+353) Ireland', phone: '353' },
  { code: 'IL', label: '(+972) Israel', phone: '972' },
  { code: 'IM', label: '(+44) Isle of Man', phone: '44' },
  { code: 'IN', label: '(+91) India', phone: '91' },
  {
    code: 'IO',
    label: '(+246) British Indian Ocean Territory',
    phone: '246',
  },
  { code: 'IQ', label: '(+964) Iraq', phone: '964' },
  {
    code: 'IR',
    label: '(+98) Iran, Islamic Republic of',
    phone: '98',
  },
  { code: 'IS', label: '(+354) Iceland', phone: '354' },
  { code: 'IT', label: '(+39) Italy', phone: '39' },
  { code: 'JE', label: '(+44) Jersey', phone: '44' },
  { code: 'JM', label: '(+1-876) Jamaica', phone: '1-876' },
  { code: 'JO', label: '(+962) Jordan', phone: '962' },
  {
    code: 'JP',
    label: '(+81) Japan',
    phone: '81',
    suggested: true,
  },
  { code: 'KE', label: '(+254) Kenya', phone: '254' },
  { code: 'KG', label: '(+996) Kyrgyzstan', phone: '996' },
  { code: 'KH', label: '(+855) Cambodia', phone: '855' },
  { code: 'KI', label: '(+686) Kiribati', phone: '686' },
  { code: 'KM', label: '(+252694254) Comoros', phone: '269' },
  {
    code: 'KN',
    label: '(+1-869) Saint Kitts and Nevis',
    phone: '1-869',
  },
  {
    code: 'KP',
    label: "(+850) Korea, Democratic People's Republic of",
    phone: '850',
  },
  { code: 'KR', label: '(+82) Korea, Republic of', phone: '82' },
  { code: 'KW', label: '(+965) Kuwait', phone: '965' },
  { code: 'KY', label: '(+1-345) Cayman Islands', phone: '1-345' },
  { code: 'KZ', label: '(+7) Kazakhstan', phone: '7' },
  {
    code: 'LA',
    label: "(+856) Lao People's Democratic Republic",
    phone: '856',
  },
  { code: 'LB', label: '(+961) Lebanon', phone: '961' },
  { code: 'LC', label: '(+1-758) Saint Lucia', phone: '1-758' },
  { code: 'LI', label: '(+423) Liechtenstein', phone: '423' },
  { code: 'LK', label: '(+94) Sri Lanka', phone: '94' },
  { code: 'LR', label: '(+231) Liberia', phone: '231' },
  { code: 'LS', label: '(+266) Lesotho', phone: '266' },
  { code: 'LT', label: '(+370) Lithuania', phone: '370' },
  { code: 'LU', label: '(+352) Luxembourg', phone: '352' },
  { code: 'LV', label: '(+371) Latvia', phone: '371' },
  { code: 'LY', label: '(+218) Libya', phone: '218' },
  { code: 'MA', label: '(+212) Morocco', phone: '212' },
  { code: 'MC', label: '(+377) Monaco', phone: '377' },
  {
    code: 'MD',
    label: '(+373) Moldova, Republic of',
    phone: '373',
  },
  { code: 'ME', label: '(+382) Montenegro', phone: '382' },
  {
    code: 'MF',
    label: '(+590) Saint Martin (French part)',
    phone: '590',
  },
  { code: 'MG', label: '(+261) Madagascar', phone: '261' },
  { code: 'MH', label: '(+692) Marshall Islands', phone: '692' },
  {
    code: 'MK',
    label: '(+389) Macedonia, the Former Yugoslav Republic of',
    phone: '389',
  },
  { code: 'ML', label: '(+223) Mali', phone: '223' },
  { code: 'MM', label: '(+95) Myanmar', phone: '95' },
  { code: 'MN', label: '(+976) Mongolia', phone: '976' },
  { code: 'MO', label: '(+853) Macao', phone: '853' },
  {
    code: 'MP',
    label: '(+1-670) Northern Mariana Islands',
    phone: '1-670',
  },
  { code: 'MQ', label: '(+596) Martinique', phone: '596' },
  { code: 'MR', label: '(+222) Mauritania', phone: '222' },
  { code: 'MS', label: '(+1-664) Montserrat', phone: '1-664' },
  { code: 'MT', label: '(+356) Malta', phone: '356' },
  { code: 'MU', label: '(+230) Mauritius', phone: '230' },
  { code: 'MV', label: '(+960) Maldives', phone: '960' },
  { code: 'MW', label: '(+265) Malawi', phone: '265' },
  { code: 'MY', label: '(+60) Malaysia', phone: '60' },
  { code: 'MZ', label: '(+258) Mozambique', phone: '258' },
  { code: 'NA', label: '(+264) Namibia', phone: '264' },
  { code: 'NC', label: '(+687) New Caledonia', phone: '687' },
  { code: 'NE', label: '(+227) Niger', phone: '227' },
  { code: 'NF', label: '(+672) Norfolk Island', phone: '672' },
  { code: 'NG', label: '(+234) Nigeria', phone: '234' },
  { code: 'NI', label: '(+505) Nicaragua', phone: '505' },
  { code: 'NL', label: '(+31) Netherlands', phone: '31' },
  { code: 'NO', label: '(+47) Norway', phone: '47' },
  { code: 'NP', label: '(+977) Nepal', phone: '977' },
  { code: 'NR', label: '(+674) Nauru', phone: '674' },
  { code: 'NU', label: '(+683) Niue', phone: '683' },
  { code: 'NZ', label: '(+64) New Zealand', phone: '64' },
  { code: 'OM', label: '(+968) Oman', phone: '968' },
  { code: 'PA', label: '(+507) Panama', phone: '507' },
  { code: 'PE', label: '(+51) Peru', phone: '51' },
  { code: 'PF', label: '(+689) French Polynesia', phone: '689' },
  { code: 'PG', label: '(+675) Papua New Guinea', phone: '675' },
  { code: 'PH', label: '(+63) Philippines', phone: '63' },
  { code: 'PK', label: '(+92) Pakistan', phone: '92' },
  { code: 'PL', label: '(+48) Poland', phone: '48' },
  {
    code: 'PM',
    label: '(+508) Saint Pierre and Miquelon',
    phone: '508',
  },
  { code: 'PN', label: '(+870) Pitcairn', phone: '870' },
  { code: 'PR', label: '(+1) Puerto Rico', phone: '1' },
  {
    code: 'PS',
    label: '(+970) Palestine, State of',
    phone: '970',
  },
  { code: 'PT', label: '(+351) Portugal', phone: '351' },
  { code: 'PW', label: '(+680) Palau', phone: '680' },
  { code: 'PY', label: '(+595) Paraguay', phone: '595' },
  { code: 'QA', label: '(+974) Qatar', phone: '974' },
  { code: 'RE', label: '(+262) Reunion', phone: '262' },
  { code: 'RO', label: '(+40) Romania', phone: '40' },
  { code: 'RS', label: '(+381) Serbia', phone: '381' },
  { code: 'RU', label: '(+7) Russian Federation', phone: '7' },
  { code: 'RW', label: '(+250) Rwanda', phone: '250' },
  { code: 'SA', label: '(+966) Saudi Arabia', phone: '966' },
  { code: 'SB', label: '(+677) Solomon Islands', phone: '677' },
  { code: 'SC', label: '(+248) Seychelles', phone: '248' },
  { code: 'SD', label: '(+249) Sudan', phone: '249' },
  { code: 'SE', label: '(+46) Sweden', phone: '46' },
  { code: 'SG', label: '(+65) Singapore', phone: '65' },
  { code: 'SH', label: '(+290) Saint Helena', phone: '290' },
  { code: 'SI', label: '(+386) Slovenia', phone: '386' },
  {
    code: 'SJ',
    label: '(+47) Svalbard and Jan Mayen',
    phone: '47',
  },
  { code: 'SK', label: '(+421) Slovakia', phone: '421' },
  { code: 'SL', label: '(+232) Sierra Leone', phone: '232' },
  { code: 'SM', label: '(+378) San Marino', phone: '378' },
  { code: 'SN', label: '(+221) Senegal', phone: '221' },
  { code: 'SO', label: '(+252) Somalia', phone: '252' },
  { code: 'SR', label: '(+597) Suriname', phone: '597' },
  { code: 'SS', label: '(+211) South Sudan', phone: '211' },
  {
    code: 'ST',
    label: '(+239) Sao Tome and Principe',
    phone: '239',
  },
  { code: 'SV', label: '(+503) El Salvador', phone: '503' },
  {
    code: 'SX',
    label: '(1-721) Sint Maarten (Dutch part)',
    phone: '1-721',
  },
  {
    code: 'SY',
    label: '(+963) Syrian Arab Republic',
    phone: '963',
  },
  { code: 'SZ', label: '(+268) Swaziland', phone: '268' },
  {
    code: 'TC',
    label: '(+1-649) Turks and Caicos Islands',
    phone: '1-649',
  },
  { code: 'TD', label: 'Chad', phone: '235' },
  {
    code: 'TF',
    label: '(+262) French Southern Territories',
    phone: '262',
  },
  { code: 'TG', label: '(+228) Togo', phone: '228' },
  { code: 'TH', label: '(+66) Thailand', phone: '66' },
  { code: 'TJ', label: '(+992) Tajikistan', phone: '992' },
  { code: 'TK', label: '(+690) Tokelau', phone: '690' },
  { code: 'TL', label: '(+670) Timor-Leste', phone: '670' },
  { code: 'TM', label: '(+993) Turkmenistan', phone: '993' },
  { code: 'TN', label: '(+216) Tunisia', phone: '216' },
  { code: 'TO', label: '(+676) Tonga', phone: '676' },
  { code: 'TR', label: '(+90) Turkey', phone: '90' },
  {
    code: 'TT',
    label: '(+1-868) Trinidad and Tobago',
    phone: '1-868',
  },
  { code: 'TV', label: '(688) Tuvalu', phone: '688' },
  {
    code: 'TW',
    label: '(+886) Taiwan, Republic of China',
    phone: '886',
  },
  {
    code: 'TZ',
    label: '(+255) United Republic of Tanzania',
    phone: '255',
  },
  { code: 'UA', label: 'Ukraine', phone: '380' },
  { code: 'UG', label: 'Uganda', phone: '256' },

  { code: 'UY', label: '(+598) Uruguay', phone: '598' },
  { code: 'UZ', label: '(+998) Uzbekistan', phone: '998' },
  {
    code: 'VA',
    label: '(+379) Holy See (Vatican City State)',
    phone: '379',
  },
  {
    code: 'VC',
    label: 'Saint Vincent and the Grenadines',
    phone: '(+58) 1-784',
  },
  { code: 'VE', label: 'Venezuela', phone: '58' },
  {
    code: 'VG',
    label: '(+1-284) British Virgin Islands',
    phone: '1-284',
  },
  {
    code: 'VI',
    label: '(+1-340) US Virgin Islands',
    phone: '1-340',
  },
  { code: 'VN', label: '(+84) Vietnam', phone: '84' },
  { code: 'VU', label: '(+678) Vanuatu', phone: '678' },
  { code: 'WF', label: '(+681) Wallis and Futuna', phone: '681' },
  { code: 'WS', label: '(+685) Samoa', phone: '685' },
  { code: 'XK', label: '(+383) Kosovo', phone: '383' },
  { code: 'YE', label: '(+967) Yemen', phone: '967' },
  { code: 'YT', label: '(+262) Mayotte', phone: '262' },
  { code: 'ZA', label: '(+27) South Africa', phone: '27' },
  { code: 'ZM', label: '(+260) Zambia', phone: '260' },
  { code: 'ZW', label: '(+263) Zimbabwe', phone: '263' },
];

export default ctr;
